### ISSUE TITLE
documentation for 0.10.0 and 0.10.1 not published

### ISSUE THREAD

**Issue by t-8ch** [bazel-contrib/rules_foreign_cc#1125]
Steps to reproduce:

* Visit https://bazelbuild.github.io/rules_foreign_cc/

Expectation:

* See links for 0.10.0 and 0.10.1

Observation: 

* Only links up to 0.9.0 are shown

**Comment by jjmaestro** [comment]
I've fixed this in #1316 and #1327 :)
