### ISSUE TITLE
cmake 3.24 is not supported

### ISSUE THREAD

**Issue by soanni86** [bazel-contrib/rules_foreign_cc#1299]
hello how can i enable support for cmake 3.24 please ?

**Comment by jsharpe** [comment]
https://github.com/bazel-contrib/rules_foreign_cc/commit/0b43bd69d9a8b0bca2768c4596e434e7fa3b1293 - versions of CMake up to the latest release should be supported.
Use the dependency macro to configure the version; note that bzlmod support for selecting the version is still pending..
